# Generated by Django 2.0.1 on 2021-10-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211029_1058'),
        ('drives', '0002_drive_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='drives.Drive')),
                ('reciever', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='users.User')),
                ('sender', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.User')),
            ],
        ),
    ]
