# Generated by Django 2.0.1 on 2021-10-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('drive_from', models.CharField(blank=True, default='', max_length=100)),
                ('drive_to', models.CharField(blank=True, default='', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('hitchhike', models.BooleanField(default=False)),
            ],
        ),
    ]
